### ISSUE TITLE
[Feature Request] Support standalone `table_name` as well as `public.table_name` table references for multi-schema databases

### ISSUE THREAD

**Issue by thomasjuhoonkim** [kysely-org/kysely-supabase#89]
*I'm so glad I found this repo. Thanks for your work in making Kysely and Supabase types compatible! If you're interested in any contributors, I'd love to help out.*

One thing postgres supports natively is table references without the `public.` schema selector and I would love if that is supported in `kysely-supabase`!

**I copied this over from the PostgreSQL documentation.**

### 5.9.2. The Public Schema 
In the previous sections we created tables without specifying any schema names. By default such tables (and other objects) are automatically put into a schema named “public”. Every new database contains such a schema. Thus, the following are equivalent:

```
CREATE TABLE products ( ... );
```

and:

```
CREATE TABLE public.products ( ... );
```

https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PUBLIC

**Comment by igalklebanov** [comment]
Hey 👋 

Thanks for raising this!

**Comment by igalklebanov** [comment]
Try it out in https://github.com/kysely-org/kysely-supabase/releases/tag/v0.2.0.

**Comment by thomasjuhoonkim** [comment]
Thanks for the changes!!
